### ISSUE TITLE
1st Report

### ISSUE THREAD

**Issue by harshalgala** [harshalgala/se17-Q#12]
- [x] Abstract (10-15 lines) - about 1 Paragraph----- Pooja
- [x] Introduction (About 15lines each) - about 2 Paragraphs -----Pooja

**Comment by harshalgala** [comment]
- [x] Study -(Literature and Statistics) ----- Q and Me --(Pages 1 to 3)
- [x] User Survey ------ Me ----- (Pages 3 to 4)
- [x] Project Goals/Concept of the project ----(Page 4 to 5)
- [x] Conclusion ----- about 2 paragraphs (Each of 10-12 pages)
- [x] References ------ (All of them) ---- Q,Pooja and Me

**Comment by harshalgala** [comment]
Start adding your respective parts here:-
[https://docs.google.com/document/d/1SANndUOP_iOz4J9uIVrf3UbmRr4E_-NpXFSshpHCVG0/edit?ts=588e0c29](url)

**Comment by harshalgala** [comment]
I have done with my work do your and please upload and compile nd meet tomorrow at 1.30pm

**Comment by gosavipooja** [comment]
Committed in the Google Doc
