### ISSUE TITLE
Meeting on Tuesday

### ISSUE THREAD

**Issue by harshalgala** [harshalgala/se17-Q#14]
Book a room for 2.oo pm to 4.00 pm
To finalize the report as well as the presentation preparations.
Pooja just reserve the room when possible.

**Comment by harshalgala** [comment]
Make the meeting tomorrow at 1.oo pm also book a room asap pooja

**Comment by gosavipooja** [comment]
Hey.. the meeting was 2:00 to 4:00 right? It's already booked.. 2315 Hunt

**Comment by harshalgala** [comment]
Q complete the compilation before the meet also we will do the final edition as well as the ppt for the Thursday cool

**Comment by harshalgala** [comment]
Guys where are you
