### ISSUE TITLE
Meeting on Tuesday 

### ISSUE THREAD

**Issue by harshalgala** [harshalgala/se17-Q#17]
From 1 to 4.
All of us should be available.
Pooja please book a room.
Start learning android basics if you don't know also this weekend on Friday we can finalize the project implementation ideas.

**Comment by gosavipooja** [comment]
Tuesday or Thursday?

**Comment by gosavipooja** [comment]
No rooms available from 1 to 4.. We'll have to sit outside somewhere!

**Comment by gosavipooja** [comment]
Room Booked for Tuesday! 2325 - 1:00 pm - 4:30 pm. Sorry for the confusion
