### ISSUE TITLE
Project Flow (If any suggestions tell me)

### ISSUE THREAD

**Issue by harshalgala** [harshalgala/se17-Q#2]
- By Sunday, Jan 15th -- Short List about 3-5 topics with proper research on literature of about 5-6 papers minimum.
- Next week we have to the survey depending on the finalized topic and before that we should at least either meet or mail to the professor or the T.A about our topics as well as problems.
-From Sunday, Jan 22nd -- Start the literature survey as by that week's end there is a submission.

**Comment by harshalgala** [comment]
Tuesday 3pm to 4.15pm meet in the library? 
To short-list 2-3 final topics.

**Comment by gosavipooja** [comment]
Yes.. Done!
