### ISSUE TITLE
Literature Survey Related 

### ISSUE THREAD

**Issue by harshalgala** [harshalgala/se17-Q#3]
We will Discuss regarding the Literature Survey on this Issue 
So this will be like a channel to discuss related. 
Find all the papers with respect to the topics needed

**Comment by gosavipooja** [comment]
Okay.. That works. But we kind of have a huge topic list here. So how do we come down to a handful?

**Comment by harshalgala** [comment]
I have created the issue for all tradeoff to check see those and if you have any others give your inputs as well.
