### ISSUE TITLE
Division on topics and discuss the details out here

### ISSUE THREAD

**Issue by harshalgala** [harshalgala/se17-Q#6]
Harshal
- Expiration Date Checker
- Car Finding in Parking Area
- Connecting Patients to Health Professionals/Doctor
  - In rural areas, the people are not able to get better health so to connect them thereby better health services
  - Can be done by making a web page as well as an application. As the rural areas just have low bandwidth so they can send symptoms via SMS services.
  - Possible to make but for checking have to check the SMS client(free is not available).
- News priority based on present Location(GPS)

Pooja
- Notification System with location sensing (Similar application as grocery crowd sourcing but for a generic purpose)
- Card Tracker Application/Software (Initially start with a wolfpack one card)
- Android Reminder/Alarm with GPS Sensor (Reminds you of what to do when you enter a particular area)
- Attendance System

Qiufeng
- Application for Grocery crowdsourcing
- Sublease finder
  - A plateform which helps you find the person who is looking for appartments
  - I know craigslist sort of does the job, but we might need a more professional plateform.
- An application which synchronizes and updates all of your emails from different account (Such as Gmail, Hotmail, Yahoo, etc.).
- Workout plan generator
  - Users need to input their basic information(heigh, weight, percentage of body fat)
  - Users need to input their expectations, such as, do they want to lose fat or build muscle
  - Expected time period. Like gain 10 lbs of muscle in 30 days
  - The program can automatically pick the right workout plan from the database

**Comment by harshalgala** [comment]
This will be the distribution of work accordingly collaborate and if any changes in topic under new or came across new topics add them on the ideas page
- On the Literature issue
 - Write about the literature and other paper or related sources.
 - On the survey issue write how can we do a survey of that particular topic.
 - For any doubts see the Tradeoff issues I have added and will add points to do while researching a topic. You both can as well write your have any solutions or suggestions.
- Write the doubts to be asked to TA and the professor on output from TA and professor section.
- Discussion on meetup do it on the meeting issue created

**Comment by timm** [comment]
i take it you are assessing each idea via

- how much lit you can find on each?
- whether or not you can find a clear eval criteria?
- whether or not you can code your ideas in an early-march timeframe?

**Comment by harshalgala** [comment]
Yes professor that is exactly what we are doing
